<h3>New material</h3>

<?php
  $form = $this->form;
  $form->prepare();
  echo $this->form()->openTag($form);
?>
<div class="form-group">
  <?php echo $this->formRow($form->get('name')); ?>
</div>
<div class="form-group">
  <?php echo $this->formRow($form->get('code')); ?>
</div>
<div class="form-group">
  <?php echo $this->formRow($form->get('group_id')); ?>
</div>
<div class="form-group">
  <?php echo $this->formRow($form->get('unit_id')); ?>
</div>

<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>
