

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Materials management</h3>
            </div>
            <div class="panel-body">                                    
                <p><a class="btn btn-success pull-right" href="<?= $this->url('materials_home') ?>">Materials</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Units management</h3>
            </div>
            <div class="panel-body">                            
                <p><a class="btn btn-success pull-right" href="<?= $this->url('units_home') ?>">Units</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Groups management</h3>
            </div>
            <div class="panel-body">
                <p><a class="btn btn-success pull-right" href="<?= $this->url('groups_home') ?>">Groups</a></p>
            </div>
        </div>
    </div>
</div>
